- name: printed varibles from files level
  hosts: mongodb
  vars_files:
   varibles.yaml
  tasks:
  - name: printed varibles from files level
    ansible.builtin.debug:
     msg: "i am learning course is {{COURSE}} and tariner is {{TRAINER}} duration is {{DURATION}}"