- name: install packages
  hosts: mongodb
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.yum:
     name: packages
     state: installed
    loop:
    - nginx
    - mailx
    - postfix
