- name: install cataloogue component
  hosts: catalogue
  become: yes
  tasks:
  - name: setup npm source
    ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash
  - name: install nodejs
    ansible.builtin.yum:
     name: nodejs
     state: installed