- name: install mongodb
  hosts: mongodb
  become: yes
  tasks:
  - name: copy files from mongodbrepo to mongodb
    ansible.builtin.copy:
     src: mongodb.repo
     dest: /etc/yum.repos.d/mongo.repo
  - name: install mongodb
    ansible.builtin.yum:
     name: mongodb-org
     state: installed
  - name: start service
    ansible.builtin.service:
    become: yes
     name: systemctl start
     state: started